// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArb8pX4UBR8RHoM52w_ZZO9gP0nNwGQtI',
    appId: '1:406661161387:web:ece76bc26f209e37f1b2ee',
    messagingSenderId: '406661161387',
    projectId: 'notably-f76a0',
    authDomain: 'notably-f76a0.firebaseapp.com',
    storageBucket: 'notably-f76a0.firebasestorage.app',
    measurementId: 'G-54VS9SMHYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk5pJErr55tJT0nqT_f0jvobBK_vn5AeE',
    appId: '1:406661161387:android:0e1462533b6ed8c3f1b2ee',
    messagingSenderId: '406661161387',
    projectId: 'notably-f76a0',
    storageBucket: 'notably-f76a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWc7Q4GnNTPIrqR8TjMbxXmH7ufHfeYoU',
    appId: '1:406661161387:ios:8397e133062ef1d9f1b2ee',
    messagingSenderId: '406661161387',
    projectId: 'notably-f76a0',
    storageBucket: 'notably-f76a0.firebasestorage.app',
    iosBundleId: 'com.notably.notably',
  );
}
